"""
Reward function for query-conditioned guidelines.

Reward: R = 1.0 if solver answer is correct, 0.0 otherwise.
Accuracy is checked via math_verify (proper math equivalence, e.g. 0.5 == 1/2).

Pipeline: planner generates guideline -> frozen solver produces answer -> check vs ground truth.

Environment variables:
  VERL_GUIDELINES_USE_MATH_VERIFY  - Use math equivalence checking (default: 1)
  VERL_GUIDELINES_SOLVER_MODEL     - Solver model path (default: Qwen/Qwen2.5-14B-Instruct-AWQ)
  VERL_GUIDELINES_SOLVER_GPU_MEM   - Solver GPU memory fraction (default: 0.9)
  VERL_GUIDELINES_SOLVER_BATCH_SIZE - Cap batch size for solver inference
  VERL_GUIDELINES_LOG_DIR          - JSONL logging directory for solver outputs

Using TRUE OFFLINE VLLM MODE:
- Load model once with vllm.LLM (no separate server)
- Batch inference directly with llm.generate()
- No HTTP/API overhead
"""

import re
import os
import json
import multiprocessing
from typing import Dict, List, Optional

# CRITICAL: Set environment variables BEFORE importing vllm
os.environ['VLLM_WORKER_MULTIPROC_METHOD'] = 'spawn'

try:
    multiprocessing.set_start_method('spawn', force=True)
except RuntimeError:
    pass

from vllm import LLM, SamplingParams
from mathruler.grader import extract_boxed_content, grade_answer

# Optional: math_verify for proper math equivalence (e.g. 0.5 == 1/2).
_math_verify_compute_score = None
_math_verify_tried = False


def _get_math_verify():
    global _math_verify_compute_score, _math_verify_tried
    if _math_verify_tried:
        return _math_verify_compute_score
    if os.environ.get("VERL_GUIDELINES_USE_MATH_VERIFY", "1").strip().lower() in ("1", "true", "yes"):
        _math_verify_tried = True
        try:
            from verl.utils.reward_score import math_verify
            _math_verify_compute_score = math_verify.compute_score
            print("")
            print(">>> MATH_VERIFY IS ACTIVE: reward accuracy uses math equivalence (e.g. 0.5 == 1/2). <<<")
            print("")
        except Exception as e:
            raise RuntimeError(
                "VERL_GUIDELINES_USE_MATH_VERIFY=1 but math_verify could not be imported. "
                "Install in the container with: pip install math-verify"
            ) from e
    else:
        _math_verify_tried = True
    return _math_verify_compute_score


# Use shared solver prompt when experiments is on PYTHONPATH (same as eval)
try:
    from experiments.prompts import SOLVER_SYSTEM_PROMPT as SYSTEM_PROMPT
except ImportError:
    SYSTEM_PROMPT = """You are a careful and disciplined problem solver that follows a given guideline to reason step by step and produce the final answer.

You are provided with:
(1) A QUESTION that needs to be solved.
(2) A GUIDELINE generated by another model that describes how to approach the problem.

Your task:
- STRICTLY follow the provided guideline to perform reasoning.
- You must first think about the reasoning process as an internal monologue before giving the final answer.
- The reasoning process MUST be enclosed within <think> </think> tags.
- The final answer MUST be placed inside \\boxed{}.
- When performing reasoning, use precise and mathematical logic, not vague explanations.
- Do NOT reveal hidden reasoning outside of the <think> block.
- If the guideline has gaps, fill them in coherently without deviating from its intent.

Format:
<think>
Your detailed internal reasoning process, including any calculations, logic, or derivations.
</think>
\\boxed{your final answer here}"""

# Global LLM instance - initialized once in offline mode
_llm_instance: Optional[LLM] = None
_sampling_params: Optional[SamplingParams] = None


def strip_think_tags(text: str) -> str:
    """Remove <think>...</think> blocks and \\boxed{...} from planner output.

    The planner should only produce step-by-step guidelines, not internal
    reasoning or final answers.  Stripping these prevents answer leakage
    from the planner into the solver prompt.
    """
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    text = re.sub(r"<think>.*", "", text, flags=re.DOTALL)
    text = re.sub(r"\\boxed\{[^}]*\}", "", text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text


def acc_reward(solver_output: str, ground_truth: str) -> float:
    """Check if solver's answer matches ground truth via math_verify (default) or mathruler."""
    math_verify_fn = _get_math_verify()
    if math_verify_fn is not None:
        try:
            return float(math_verify_fn(solver_output, ground_truth))
        except Exception:
            pass
    answer = extract_boxed_content(solver_output)
    return 1.0 if grade_answer(answer, ground_truth) else 0.0


def _get_solver_model_path() -> str:
    """Solver model path: VERL_GUIDELINES_SOLVER_MODEL env or default."""
    return os.environ.get("VERL_GUIDELINES_SOLVER_MODEL", "Qwen/Qwen2.5-14B-Instruct-AWQ")


def _get_solver_gpu_mem() -> float:
    """Solver GPU memory utilization."""
    try:
        return float(os.environ.get("VERL_GUIDELINES_SOLVER_GPU_MEM", "0.9"))
    except ValueError:
        return 0.9


def init_offline_llm(
    model_path: str | None = None,
    tensor_parallel_size: int = 1,
    gpu_memory_utilization: float = None,
    max_model_len: int = 8192,
    dtype: str = "float16",
    **kwargs
) -> LLM:
    """Initialize the LLM in TRUE OFFLINE MODE using vllm.LLM."""
    global _llm_instance, _sampling_params
    if model_path is None:
        model_path = _get_solver_model_path()
    if gpu_memory_utilization is None:
        gpu_memory_utilization = _get_solver_gpu_mem()
    if _llm_instance is None:
        solver_gpu_id = os.environ.get("VERL_GUIDELINES_SOLVER_GPU_ID")
        if solver_gpu_id is not None:
            os.environ["CUDA_VISIBLE_DEVICES"] = solver_gpu_id
            print(f"[OFFLINE VLLM] Using GPU(s) for solver: {solver_gpu_id}")
        os.environ["VLLM_USE_V1"] = "0"

        quantization = None
        model_lower = model_path.lower()
        if "gptq" in model_lower:
            quantization = "gptq"
            dtype = "half"
        elif "awq" in model_lower:
            quantization = "awq_marlin"
            dtype = "half"

        print(f"[OFFLINE VLLM] Initializing LLM with model: {model_path}")
        print(f"[OFFLINE VLLM] Config: tp={tensor_parallel_size}, gpu_mem={gpu_memory_utilization}, dtype={dtype}, quantization={quantization}")

        _llm_instance = LLM(
            model=model_path,
            tensor_parallel_size=tensor_parallel_size,
            gpu_memory_utilization=gpu_memory_utilization,
            max_model_len=max_model_len,
            dtype=dtype,
            quantization=quantization,
            trust_remote_code=True,
            enforce_eager=True,
            **kwargs
        )

        _sampling_params = SamplingParams(
            temperature=0.0,
            max_tokens=3072,
            top_p=1.0,
        )

        print(f"[OFFLINE VLLM] Model loaded successfully")

    return _llm_instance


def get_llm() -> LLM:
    """Get the global LLM instance. Initializes if needed."""
    global _llm_instance
    if _llm_instance is None:
        return init_offline_llm(model_path=_get_solver_model_path())
    return _llm_instance


def get_sampling_params() -> SamplingParams:
    """Get the global sampling params."""
    global _sampling_params
    if _sampling_params is None:
        init_offline_llm()
    return _sampling_params


def _solver_messages(question: str, guideline: str):
    """Build chat messages for Qwen/instruct models."""
    guideline = strip_think_tags(guideline)
    user_content = (
        f"Question: {question}\n\nGuideline: {guideline}\n\n"
        "Please strictly follow the Guideline to solve the Question. "
        "Put reasoning inside <think> </think> and final answer inside \\boxed{}."
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def call_solver(guideline: str, question: str) -> str:
    """Call frozen solver using OFFLINE VLLM with chat format."""
    llm = get_llm()
    sampling_params = get_sampling_params()
    messages = _solver_messages(question, guideline)

    try:
        if hasattr(llm, "chat"):
            outputs = llm.chat(messages=[messages], sampling_params=sampling_params, use_tqdm=False)
        else:
            prompt = f"{SYSTEM_PROMPT}\n\nQuestion: {question}\n\nGuideline: {guideline}"
            outputs = llm.generate([prompt], sampling_params, use_tqdm=False)

        if outputs and len(outputs) > 0 and outputs[0].outputs:
            generated_text = outputs[0].outputs[0].text
            if generated_text is not None and len(generated_text.strip()) > 0:
                return generated_text
        if not hasattr(call_solver, "_empty_count"):
            call_solver._empty_count = 0
        call_solver._empty_count += 1
        if call_solver._empty_count <= 5:
            print(f"[OFFLINE VLLM] Warning: Solver returned empty [count={call_solver._empty_count}]")
        return ""
    except Exception as e:
        print(f"[OFFLINE VLLM] Error during solver inference: {e}")
        import traceback
        traceback.print_exc()
        return ""


def compute_score(
    predict_str: str,
    ground_truth: str,
    extra_info: dict = None,
    **kwargs,
) -> float:
    """Compute reward for a single guideline. R = 1.0 if correct, 0.0 otherwise."""
    if extra_info is None or 'question' not in extra_info:
        if not hasattr(compute_score, '_warned_missing_question'):
            print(f"ERROR: extra_info missing 'question' field. keys: {list(extra_info.keys()) if extra_info else 'None'}")
            compute_score._warned_missing_question = True
        return 0.0

    question = extra_info['question']
    solver_output = call_solver(predict_str, question)

    if not solver_output:
        if not hasattr(compute_score, '_warned_api_fail'):
            print(f"ERROR: Solver returned empty. Guideline: {predict_str[:100]}... Question: {question[:100]}...")
            compute_score._warned_api_fail = True
        return 0.0

    reward = acc_reward(solver_output, ground_truth)

    if not hasattr(compute_score, '_log_count'):
        compute_score._log_count = 0
    if compute_score._log_count < 10:
        print(f"[REWARD {compute_score._log_count}] R={reward:.0f} | Q: {question[:60]}... | GT: {ground_truth}")
        compute_score._log_count += 1

    return reward


def _run_solver_batch(
    llm, sampling_params,
    batch_guidelines: List[str],
    batch_questions: List[str],
    batch_ground_truths: List[str],
) -> List[float]:
    """Run one vLLM batch and return rewards. R = 1.0 if correct, 0.0 otherwise."""
    batch_messages = [_solver_messages(q, g) for g, q in zip(batch_guidelines, batch_questions)]
    try:
        if hasattr(llm, "chat"):
            outputs = llm.chat(messages=batch_messages, sampling_params=sampling_params, use_tqdm=True)
        else:
            prompts = [f"{SYSTEM_PROMPT}\n\nQuestion: {q}\n\nGuideline: {g}" for g, q in zip(batch_guidelines, batch_questions)]
            outputs = llm.generate(prompts, sampling_params, use_tqdm=True)
    except Exception as e:
        print(f"[OFFLINE VLLM] Batch inference failed: {e}")
        import traceback
        traceback.print_exc()
        outputs = [None] * len(batch_messages)
    if len(outputs) < len(batch_messages):
        outputs = list(outputs) + [None] * (len(batch_messages) - len(outputs))

    rewards = []
    solver_texts = []

    for idx, (output, guideline, question, gt) in enumerate(
        zip(outputs, batch_guidelines, batch_questions, batch_ground_truths)
    ):
        solver_output = ""
        if output is not None and output.outputs:
            text = output.outputs[0].text
            if text is not None and text.strip():
                solver_output = text

        reward = acc_reward(solver_output, gt) if solver_output else 0.0
        rewards.append(reward)
        solver_texts.append(solver_output)

    # JSONL logging: set VERL_GUIDELINES_LOG_DIR to enable
    log_dir = os.environ.get("VERL_GUIDELINES_LOG_DIR", "").strip()
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)
        log_path = os.path.join(log_dir, "solver_outputs.jsonl")
        if not hasattr(_run_solver_batch, "_step_counter"):
            _run_solver_batch._step_counter = 0
        _run_solver_batch._step_counter += 1
        step = _run_solver_batch._step_counter
        with open(log_path, "a", encoding="utf-8") as f:
            for i in range(len(rewards)):
                row = {
                    "step": step,
                    "question": batch_questions[i],
                    "guideline": batch_guidelines[i],
                    "solver_output": solver_texts[i],
                    "ground_truth": batch_ground_truths[i],
                    "reward": rewards[i],
                }
                f.write(json.dumps(row, ensure_ascii=False) + "\n")

    return rewards


def compute_rewards_batch(
    guidelines: List[str],
    questions: List[str],
    ground_truths: List[str],
    **kwargs
) -> List[float]:
    """Batch reward computation for VERL. R = 1.0 if correct, 0.0 otherwise (via math_verify)."""
    cap = os.environ.get("VERL_GUIDELINES_SOLVER_BATCH_SIZE", "").strip()
    chunk_size = int(cap) if cap.isdigit() and int(cap) > 0 else len(guidelines)

    llm = get_llm()
    sampling_params = get_sampling_params()

    all_rewards: List[float] = []

    for start in range(0, len(guidelines), chunk_size):
        end = min(start + chunk_size, len(guidelines))
        g_slice = guidelines[start:end]
        q_slice = questions[start:end]
        gt_slice = ground_truths[start:end]
        print(f"[OFFLINE VLLM] Batch solver: running inference for {len(g_slice)} prompts...")
        chunk_rewards = _run_solver_batch(llm, sampling_params, g_slice, q_slice, gt_slice)
        all_rewards.extend(chunk_rewards)

    n = len(all_rewards)
    avg_r = sum(all_rewards) / n if n else 0.0
    std_r = (sum((r - avg_r) ** 2 for r in all_rewards) / n) ** 0.5 if n > 1 else 0.0
    n_correct = sum(1 for r in all_rewards if r > 0)
    print(f"[OFFLINE VLLM] Batch solver done. {n} samples, accuracy: {n_correct}/{n} ({n_correct/n:.1%}), avg reward: {avg_r:.3f} std: {std_r:.3f}")

    return all_rewards
